# Generated by Django 6.0 on 2025-12-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
