# Generated by Django 6.0 on 2025-12-11 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_user_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
