# Generated by Django 6.0 on 2026-01-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_scrap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='seller',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default=9867948912, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Scrap',
        ),
    ]
