# Generated by Django 6.0 on 2026-01-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
