# Generated by Django 6.0 on 2026-01-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_profile_address_alter_profile_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationotp',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='registrationotp',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='registrationotp',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registrationotp',
            name='role',
        ),
        migrations.RemoveField(
            model_name='registrationotp',
            name='username',
        ),
        migrations.AlterField(
            model_name='registrationotp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
