# Generated by Django 6.0 on 2026-02-05 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_registrationotp_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='scrap',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='is_assigned',
        ),
        migrations.AddField(
            model_name='scrap',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='posted', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='scrap_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('metal', 'Metal'), ('iron', 'Iron'), ('copper', 'Copper'), ('electronics', 'E-Waste'), ('glass', 'Glass'), ('mixed', 'Mixed Scrap')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.scrap')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PickupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('pickup_day', models.CharField(max_length=20)),
                ('pickup_time', models.TimeField()),
                ('collector_name', models.CharField(max_length=100)),
                ('collector_phone', models.CharField(max_length=15)),
                ('collector_email', models.EmailField(max_length=254)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.pickuprequest')),
            ],
        ),
    ]
