# Generated by Django 6.0 on 2026-02-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_pickuprequest_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupschedule',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
    ]
