# Generated by Django 6.0 on 2026-02-17 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_pickupschedule_pickup_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupschedule',
            name='pickup_day',
        ),
        migrations.RemoveField(
            model_name='pickupschedule',
            name='pickup_time',
        ),
        migrations.AlterField(
            model_name='pickupschedule',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pickuprequest'),
        ),
    ]
