# Generated by Django 6.0 on 2026-02-17 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_pickupschedule_pickup_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupschedule',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='home.pickuprequest'),
        ),
    ]
