# Generated by Django 6.0 on 2026-02-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_pickupschedule_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='collection_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
