# Generated by Django 6.0 on 2026-02-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_pickuprequest_collection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuprequest',
            name='collection_status',
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
