# Generated by Django 6.0 on 2026-02-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_scrapprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapprice',
            old_name='price_per_kg',
            new_name='price',
        ),
    ]
