# Generated by Django 6.0 on 2026-02-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_rename_price_per_kg_scrapprice_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapprice',
            old_name='price',
            new_name='price_per_kg',
        ),
    ]
