# Generated by Django 6.0 on 2026-03-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_price_scrapprice_price_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='scrap_image',
            field=models.ImageField(blank=True, null=True, upload_to='scrap_images/'),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='scrap_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('aluminium', 'Aluminium'), ('iron', 'Iron'), ('brass', 'Brass'), ('copper', 'Copper'), ('electronics', 'E-Waste'), ('glass', 'Glass'), ('mixed', 'Mixed Scrap')], max_length=50),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='status',
            field=models.CharField(choices=[('posted', 'Posted'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='posted', max_length=20),
        ),
    ]
