# Generated by Django 6.0 on 2026-03-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_scrap_scrap_image_alter_scrap_scrap_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='address',
        ),
        migrations.AddField(
            model_name='scrap',
            name='building_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrap',
            name='flat_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='area',
            field=models.CharField(max_length=200),
        ),
    ]
