# Generated by Django 6.0 on 2026-03-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_scrap_address_scrap_building_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='flat_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='building_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
