# Generated by Django 6.0 on 2026-03-07 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_pickupreceipt_receiptitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptitem',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pickupreceipt'),
        ),
    ]
