# Generated by Django 6.0 on 2026-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_pickuprequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectorreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scrap',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='scrapprice',
            name='scrap_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('aluminium', 'Aluminium'), ('iron', 'Iron'), ('brass', 'Brass'), ('copper', 'Copper'), ('electronics', 'E-Waste'), ('glass', 'Glass'), ('mixed', 'Mixed Scrap')], max_length=50),
        ),
        migrations.DeleteModel(
            name='PickupSchedule',
        ),
    ]
